services:
  api:
    build:
      context: src
      dockerfile: docker/dockerfile
    command: uvicorn config.asgi:application --workers 1 --host 0.0.0.0 --port 8000 --reload --reload-include *.html
    volumes:
      - ./src/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - TZ=Asia/Kathmandu
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - SERVER_TYPE=LOCAL
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - ./src/config/.env
    container_name: attendance_backend

  db:
    container_name: attendance_db
    image: postgis/postgis:14-3.3
    environment:
      - POSTGRES_DB=attendancedb
      - POSTGRES_USER=attendanceadmin
      - POSTGRES_PASSWORD=Admin@1234
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
